

{ name: "chmt",
  label: "Приветствие",
  phrase: "ЧМТ",
  isChecked: false,
},
,

{ name: "chmt",
  label: "ЧМТ",
  phrase: "ЧМТ",
  isChecked: false,
},
{ name: "chmt",
  label: "ОНМК",
  phrase: "ОНМК",
  isChecked: false,
},
{ name: "chmt",
  label: "эпи-активность",
  phrase: "эпи-активность",
  isChecked: false,
},
{ name: "chmt",
  label: "нарушение ритма",
  phrase: "нарушение ритма",
  isChecked: false,
},
{ name: "chmt",
  label: "наблюдение у психиатра",
  phrase: "наблюдение у психиатра",
  isChecked: false,
},
{ name: "chmt",
  label: "гипотимные состояния",
  phrase: "гипотимные состояния",
  isChecked: false,
},
{ name: "chmt",
  label: "алкоголизация",
  phrase: "алкоголизация",
  isChecked: false,
},
{ name: "chmt",
  label: "злоупотребление снотворными",
  phrase: "злоупотребление снотворными",
  isChecked: false,
},
{ name: "chmt",
  label: "нарушения памяти",
  phrase: "нарушения памяти",
  isChecked: false,
},
{ name: "chmt",
  label: "спутанность дома",
  phrase: "спутанность дома",
  isChecked: false,
},
{ name: "chmt",
  label: "спутанность на отделении",
  phrase: "спутанность на отделении",
  isChecked: false,
},
{ name: "chmt",
  label: "падения",
  phrase: "падения",
  isChecked: false,
},
{ name: "chmt",
  label: "психотравма",
  phrase: "психотравма",
  isChecked: false,
},
{ name: "chmt",
  label: "объективный анамнез неизвестен",
  phrase: "объективный анамнез неизвестен"
  isChecked: false,
},

